###
GET http://n652960.yclients.com/api/v1/book_staff/617387
authorization: Bearer yusw3yeu6hrr4r9j3gw6

###
GET http://n652960.yclients.com/api/v1/book_staff_seances/617387/1789971
authorization: Bearer yusw3yeu6hrr4r9j3gw6

###
GET https://n652960.yclients.com/api/v1/book_dates/617387?staff_id=1789971&date=2022-02-02
authorization: Bearer yusw3yeu6hrr4r9j3gw6

###
GET https://n652960.yclients.com/api/v1/book_times/617387/1789971/2022-02-05
authorization: Bearer yusw3yeu6hrr4r9j3gw6


###
GET https://n652960.yclients.com/api/v1/book_times/617387/1789963/2022-02-04
authorization: Bearer yusw3yeu6hrr4r9j3gw6
