###
GET http://n652960.yclients.com/api/v1/book_staff/{{studio-id}}
authorization:{{auth-token}}

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
});
%}

###
GET http://n652960.yclients.com/api/v1/book_staff_seances/{{studio-id}}/{{staff-id}}
authorization:{{auth-token}}

###
GET https://n652960.yclients.com/api/v1/book_dates/{{studio-id}}?staff_id={{staff-id}}&date=2022-02-02
authorization:{{auth-token}}

###
GET https://n652960.yclients.com/api/v1/book_times/{{studio-id}}/{{staff-id}}/2022-02-05
authorization:{{auth-token}}


###
GET https://n652960.yclients.com/api/v1/book_times/{{studio-id}}/1789963/2022-02-04
authorization:{{auth-token}}
